name = "download-center"
main = "src/worker.js"
compatibility_date = "2025-12-01"

assets = { directory = "./public", binding = "ASSETS", run_worker_first = ["/api/*", "/d/*", "/admin/*"] }

[[d1_databases]]
binding = "DB"
database_name = "download-db"
database_id = "25b8e3ad-83d3-443b-a7eb-7c7811239afe"

[[kv_namespaces]]
binding = "download-kv"
id = "81739ffac7a64296ba7af8aeae1c4907"
